### ISSUE TITLE
Publishing on crates.io

### ISSUE THREAD

**Issue by jof** [Shock-1/sam3x8e-hal#2]
Hello -- I like this library, and I would like to use a bit, and with Arduino Due, I imagine that others would like to as well.

I would like to have this crate on crates.io, but I didn't want to steal the name if you would like to publish it first.
Would you be ok with me publishing this crate? Would you like to own it?

**Comment by Shock-1** [comment]
I am fine with publishing the library. And really thanks for liking this library. I would love to continue working on it, if other people are interested. As for publishing it I would recommend naming it somewhat like _sam3x8e-hal alt_. Since there are people with more complete implementations out there, and here we can explore the design space more. Would love to hear your opinions.
Also we can jointly own a crate as well.

**Comment by jof** [comment]
Is there a more complete implementation of the embedded_hal for sam3x8e somewhere?

From what I could tell, you had the most complete support that I could find.

**Comment by Shock-1** [comment]
i think there are two, here are the links
[https://github.com/compenguy/atsam3xa](https://github.com/compenguy/atsam3xa)
[https://github.com/inferiorhumanorgans/sam3x8e-rs](https://github.com/inferiorhumanorgans/sam3x8e-rs)
